name: Github packages publish

on: workflow_dispatch

jobs:

  publish-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16, 18, 20, 21 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm run container publish debian:buster ${{ matrix.node-version }}
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}


  publish-winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x, 21.x ]
        platforms: [ windows-2019, macos-11 ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: npm install --ignore-scripts
    - run: npm install node-gyp
    - run: npx @mapbox/node-pre-gyp configure
    - run: npx @mapbox/node-pre-gyp build -j max
    - run: npm test
    - run: npx @mapbox/node-pre-gyp package
    - run: npx @mmomtchev/node-pre-gyp-github publish
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
