name: Github packages publish

on: workflow_dispatch

jobs:

  publish-linux-old:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18, 20 ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm run container publish debian-archive:buster ${{ matrix.node-version }}
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}


  publish-linux-new:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22, 23, 24 ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm run container publish debian:bullseye ${{ matrix.node-version }}
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}


  publish-winmac:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 18.x, 20.x, 22.x, 23.x, 24.x ]
        platforms: [ windows-2022, macos-13, macos-15 ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: npm install --ignore-scripts
    - run: npm install node-gyp
    - run: npx @mapbox/node-pre-gyp configure
    - run: npx @mapbox/node-pre-gyp build -j max
    - run: npm test
    - run: npx @mapbox/node-pre-gyp package
    - run: npx @mmomtchev/node-pre-gyp-github publish
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
